name: 📦 Helm Chart Build

on:
  push:
    branches:
      - 'dev'
  pull_request:
    branches:
      - 'dev'
      - 'main'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4.1.0

      - name: Helm Dependency update
        run: helm dependency update scraparr/ --debug

      - name: Helm Template
        run: helm template scraparr scraparr/ --debug

      - name: Create Package
        run: helm package scraparr/
